language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
install:
  - pip install -e .
  - pip install --use-mirrors -r requirements-dev.txt Django==$DJANGO_VERSION
script:
  - django-admin.py test --settings=runcommands.test_settings runcommands
  - flake8 runcommands
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.5
